[package]
name = "dask_planner"
repository = "https://github.com/dask-contrib/dask-sql"
version = "0.1.0"
description = "Bindings for DataFusion used by Dask-SQL"
readme = "README.md"
license = "Apache-2.0"
edition = "2021"
rust-version = "1.62"

[dependencies]
arrow = { version = "29.0.0", features = ["prettyprint"] }
async-trait = "0.1.63"
colored = "2.0.0"
#datafusion = { git = "https://github.com/jdye64/arrow-datafusion", branch = "sized_planvisitor" }
#datafusion-common = { git = "https://github.com/jdye64/arrow-datafusion", branch = "sized_planvisitor" }
#datafusion-expr = { git = "https://github.com/jdye64/arrow-datafusion", branch = "sized_planvisitor" }
#datafusion-optimizer = { git = "https://github.com/jdye64/arrow-datafusion", branch = "sized_planvisitor" }
#datafusion-sql = { git = "https://github.com/jdye64/arrow-datafusion", branch = "sized_planvisitor" }
datafusion = "16.1.0"
datafusion-common = "16.1.0"
datafusion-expr = "16.1.0"
datafusion-optimizer = "16.1.0"
datafusion-sql = "16.1.0"
env_logger = "0.10"
log = "^0.4"
mimalloc = { version = "*", default-features = false }
parking_lot = "0.12"
pyo3 = { version = "0.18.0", features = ["extension-module", "abi3", "abi3-py38"] }
rand = "0.8"
tokio = { version = "1.24", features = ["macros", "rt", "rt-multi-thread", "sync", "fs", "parking_lot"] }
uuid = { version = "1.2", features = ["v4"] }

[lib]
crate-type = ["cdylib"]
